services:
  theme:
    container_name: lumeo-base-theme
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - lumeo_theme_volume:/app/dist
      - ./:/app
      - /app/node_modules
    tty: true

volumes:
  lumeo_theme_volume:
    external: true